Change transform error to accept parse results
apiaryio/metamorphoses pull request #70
Opened 2016-12-07 18:36 UTC by kylef

Currently the error handling process in Apiary/Metamorphoses is broken for some formats (API Elements). In some cases the error information (line, location) is not there and in other places the error passed to Metamorphoses from Apiary isn't a real error.

I am preparing a counter-pr to go in Apiary which can be reviewed alongside this PR.

I have added tests for API Elements error handling, which are now correctly extracted from a parse result. I did not change the behaviour for Apiary Blueprint, since we should just remove it: https://github.com/apiaryio/metamorphoses/pull/69

2016-12-07 18:38 UTC, kylef commented on src/adapters/refract-adapter.coffee
> +    sourceMap = errors[0]?.attributes?.sourceMap?[0]?.content?[0]
This is a bit horrible, if someone who knows [lodash-api-description](https://github.com/apiaryio/lodash-api-description) better than me has any suggestions I'd love to hear.

I could make this much better using minim but didn't want to pull in an additional dependency. I do think we should switch all uses of lodash-api-description to minim in the future (separate discussion).

2016-12-10 11:41 UTC, pksunkara requested changes
Can you also please rebase?

2016-12-10 11:41 UTC, pksunkara commented on README.md
> +  // transform the error parse result into an error
`Retrieves the error from parse result`

2016-12-10 11:41 UTC, pksunkara commented on src/adapters/refract-adapter.coffee
> +    sourceMap = errors[0]?.attributes?.sourceMap?[0]?.content?[0]
You don't need `?` at `errors[0]?`

2016-12-10 11:41 UTC, pksunkara commented on src/adapters/refract-adapter.coffee
> +      code: errors?[0]?.attributes?.code or 1
You can replace `errors?[0]?` with `errors[0]` in the above 2 lines.

2016-12-10 11:41 UTC, pksunkara commented on src/adapters/refract-adapter.coffee
> +      location: [{index, length}]
Why is the location taking the first source map only? It should have all the sourcemaps.

2016-12-10 11:41 UTC, pksunkara commented on test/transformation-test.coffee
> +    if err
Would this logic work when protagonist sends the error in callback?

2016-12-10 19:29 UTC, kylef commented on test/transformation-test.coffee
> +    if err
Protagonist doesn't though, the test would start failing if that was the case and then this + the next few lines could be removed.

2016-12-10 19:29 UTC, kylef commented on README.md
> +  // transform the error parse result into an error
I'm not sure, it's not retrieving it, since it is returning a different error derived from the error in the parse result in some cases.

2016-12-10 19:29 UTC, kylef commented on src/adapters/refract-adapter.coffee
> +      code: errors?[0]?.attributes?.code or 1
95233a4

2016-12-10 19:29 UTC, kylef commented on src/adapters/refract-adapter.coffee
> +      location: [{index, length}]
97e4f2a

2016-12-10 19:38 UTC, pksunkara commented on test/transformation-test.coffee
> +    if err
Oh, yeah, I think we removed that recently.

2016-12-10 19:38 UTC, pksunkara approved these changes

2016-12-13 13:15 UTC, kuba-kubula approved these changes
just a minor comment.
looks ok else.

then please release as new minor-version (in a separate PR).

2016-12-13 13:15 UTC, kuba-kubula commented on test/transformation-test.coffee
> +      result.error = err
can we be sure `result` is always an object when `err` is present?
(trying to avoid `TypeError: cannot set error of null`.

2016-12-13 13:15 UTC, pksunkara commented
@kylef Do you want to rebase this?

2016-12-13 21:22 UTC, kylef commented on test/transformation-test.coffee
> +      result.error = err
`protagonist.parse` will throw for type errors as out is now (https://github.com/apiaryio/protagonist/blob/master/src/parse_async.cc#L37-L58). There is separate handling for user vs programming errors.

From Apiary side, the parse result from the API (serialised to/from JSON) will already contain the error as the format in API Blueprint AST (https://github.com/apiaryio/api-blueprint-ast/blob/master/Parse%20Result.md#error) as demonstrated in [API Blueprint AST test fixture](https://github.com/apiaryio/apiary/blob/b58276c7293e3059b46852fcc84a024b294889d8/test/fixtures/parser/invalid-api-blueprint.coffee#L27).

2016-12-13 21:23 UTC, merged