Merge multiple headers with the same key into one
apiaryio/metamorphoses pull request #82
Opened 2017-02-14 14:05 UTC by michalholasek

This PR fixes issue with dropped header values during A1 -> legacy transformation in API Blueprint adapter.

2017-02-14 14:05 UTC, michalholasek commented
![](https://github.trello.services/images/mini-trello-icon.png) [Console fails to render header](https://trello.com/c/XQZXbl8P/279-console-fails-to-render-header)

2017-02-14 14:09 UTC, pksunkara commented
Please make the change for refract adapter too.

2017-02-14 14:10 UTC, pksunkara commented
Otherwise lgtm.

2017-02-14 16:38 UTC, pksunkara approved these changes

2017-02-14 16:49 UTC, kylef requested changes

2017-02-14 16:49 UTC, kylef commented on src/adapters/api-blueprint-adapter.coffee
> +#     { name: 'Set-Cookie', value: 'abcde; Alan Turing' }
Shouldn't this be `abcde, Alan Turing` not `abcde; Alan Turing` according to [RFC2616](https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2)?

> Multiple message-header fields with the same field-name MAY be present in a message if and only if the entire field-value for that header field is defined as a comma-separated list [i.e., #(values)]. It MUST be possible to combine the multiple header fields into one "field-name: field-value" pair, without changing the semantics of the message, by appending each subsequent field-value to the first, each separated by a comma.

2017-02-14 16:55 UTC, kylef commented on src/adapters/api-blueprint-adapter.coffee
> +#     { name: 'Set-Cookie', value: 'abcde; Alan Turing' }
Note, `;` is already used as a token separator in both `Set-Cookie` and `Link` headers.

Example, the following `Link` headers are equivalent:

```
Link: <https://api.github.com/user/repos?page=3&per_page=100>; rel="next",
      <https://api.github.com/user/repos?page=50&per_page=100>; rel="last"
```

```
Link: <https://api.github.com/user/repos?page=3&per_page=100>; rel="next"
Link: <https://api.github.com/user/repos?page=50&per_page=100>; rel="last"
```

Whereas joining them by `;` will change the definition.

2017-02-14 17:02 UTC, kylef commented
The linked Trello card (![](https://github.trello.services/images/mini-trello-icon.png) [Console fails to render header](https://trello.com/c/XQZXbl8P/279-console-fails-to-render-header)) is about the console not documentation coming from the API specification. I don't think this fixes the users problem unless I'm missing some counter Apiary PR?

2017-02-14 17:07 UTC, michalholasek commented on src/adapters/api-blueprint-adapter.coffee
> +#     { name: 'Set-Cookie', value: 'abcde; Alan Turing' }
Right, thanks. Reflected in https://github.com/apiaryio/metamorphoses/pull/82/commits/64b29b68e66fcc98d56fe14aa8944e4b4475359a.

2017-02-14 17:10 UTC, michalholasek commented
You are right, changes made in https://github.com/apiaryio/apiary/commit/7b87ca7ef96cffda4304b77ca355b6dc9d770c42 fix given problem.

2017-02-14 17:10 UTC, kylef approved these changes

2017-02-14 17:12 UTC, kylef commented
I wonder if this would cause any problems in the traffic inspector. Since a server may send two separate headers and the application AST would contain the headers concatenated together and the diff of the requests may show incorrectly.

/c @honzajavorek

2017-02-14 17:42 UTC, kylef commented
To demonstrate what I mentioned with traffic inspector. We can reproduce what I mention by creating a blueprint with comma separated link header (after this PR, the headers would be merged as I showed below in the AST and not source blueprint).

```apib
HOST: http://httpbin.org

# My API
## GET /response-headers?Link=a&Link=b

+ Response 200 (application/json)
    + Headers
    
            Link: A, B
            
    + Body
    
            {
                "Content-Length": "105", 
                "Content-Type": "application/json", 
                "Link": [
                "a", 
                "b"
                ]
            }
```

You can then create a request using the debugging proxy and view it in the traffic inspector. The response will be marked as orange as the headers mismatch the server due to being joined.

![screen shot 2017-02-14 at 17 40 56](https://cloud.githubusercontent.com/assets/44164/22941274/c5ef056a-f2dc-11e6-93d4-16201cdf32a4.png)

2017-02-14 17:45 UTC, kylef requested changes
Since this would cause a bug with the traffic inspector when a user uses separate multiple headers in their API Description document and API implementation.

2017-02-14 17:51 UTC, kylef approved these changes

2017-02-14 17:56 UTC, kylef commented
IMO, If a user explicitly written their headers separately the documentation should render as such. I think internally we should change the application AST to support this and the traffic inspector/dredd should support validating headers that are joined/separate.

2017-02-15 09:35 UTC, honzajavorek commented
I agree we should support multiple headers both in the inspector and Dredd. There's related issue in Dredd: https://github.com/apiaryio/dredd/issues/356 I'm not sure what's the current expected behavior in the Inspector, Mock Server, and Debugging Proxy, as of now. I didn't find any existing tests on the topic. I don't think I can currently provide much support to this though alongside my other tasks.

This is a cross-team dependency we should probably discuss it on Monday. Also should be coordinated by @netmilk.

If I can share my personal dreams here, in the best case, there would be integration tests with at least couple of scenarios (multiple headers defined separately, multiple headers defined joined) verifying the desired behavior (discussed and specified by @netmilk) for all affected products (Inspector, Mock Server, and Debugging Proxy). In case the reality wouldn't comply with such tests, product would be fixed.

2017-02-21 14:32 UTC, XVincentX commented
I forgot to bring this one in the past TL Sync 😢

2017-02-21 14:39 UTC, XVincentX commented on test/transformation-test.coffee
> +          it('response has correctly merged headers', ->
I'd probably put a couple of new lines between tests.

2017-03-27 09:59 UTC, XVincentX commented
I guess we can close this, isn't it? @michalholasek

2017-03-27 10:08 UTC, kylef commented
> I guess we can close this

Yes, or at least all changes should cover the API Elements adapter since as off today we've hit 100% rollout and API Blueprint AST adapter is not used.

2017-04-10 19:54 UTC, michalholasek commented
@XVincentX Yes we can. Replaced with https://github.com/apiaryio/metamorphoses/pull/83.

2017-04-10 19:54 UTC, closed without merging