Add headers1A property to the AST for both API Blueprint and Refract adapters
apiaryio/metamorphoses pull request #83
Opened 2017-04-10 19:52 UTC by michalholasek

Changes made in this PR are needed for support of multiple headers (with the same key / header name) in the core app.

2017-04-10 19:55 UTC, michalholasek commented
![](https://github.trello.services/images/mini-trello-icon.png) [Console fails to render header](https://trello.com/c/XQZXbl8P/279-console-fails-to-render-header)

2017-04-11 02:21 UTC, pksunkara commented
Looks good, but please add minor test for this.

2017-04-11 09:04 UTC, XVincentX requested changes
Please add a test for checking that when you're putting two headers, those get persisted in the new property.

2017-04-11 09:04 UTC, XVincentX commented on CHANGELOG.md
> +- `headers1A` property added to the Request / Response transaction pairs for both API Blueprint and Refract adapters.
Please explain why we made that.

2017-04-11 09:04 UTC, XVincentX commented on src/adapters/refract/transformTransactions.coffee
> +    [requestHeaders, requestHeaders1A] = getHeaders(httpRequest)
I think we should return an object rather than an array - it's confusing.

2017-04-11 09:06 UTC, pksunkara commented on src/adapters/refract/transformTransactions.coffee
> +    [requestHeaders, requestHeaders1A] = getHeaders(httpRequest)
Actually, `getHeaders` should probably only return `headers` and we can add `getHeaders1A` to return `headers1A`

2017-04-11 09:07 UTC, XVincentX commented on src/adapters/refract/transformTransactions.coffee
> +    [requestHeaders, requestHeaders1A] = getHeaders(httpRequest)
You decide on that, let's just not use arrays as a returning pattern as long it's not really same type.

2017-04-11 09:23 UTC, michalholasek commented on src/adapters/refract/transformTransactions.coffee
> +    [requestHeaders, requestHeaders1A] = getHeaders(httpRequest)
I agree that returning arrays with two (or more) different data structures is not very elegant and good for readibility, but I wanted to keep it DRY. I will add `getHeaders1A`.

2017-04-11 12:25 UTC, michalholasek commented on CHANGELOG.md
> +- `headers1A` property added to the Request / Response transaction pairs for both API Blueprint and Refract adapters.
Addressed.

2017-04-11 12:25 UTC, michalholasek commented on src/adapters/refract/transformTransactions.coffee
> +    [requestHeaders, requestHeaders1A] = getHeaders(httpRequest)
Addressed.

2017-04-11 12:48 UTC, pksunkara approved these changes

2017-04-11 15:17 UTC, XVincentX commented on test/transformation-test.coffee
> +            assert.equal(setCookieHeaders.length, 3)
Could you please check that the value is different for all these? (Make sure it's not being overwritten)

2017-04-11 15:18 UTC, XVincentX commented on package.json
> +  "version": "0.13.8",
This is a minor release, not a patch. It's adding a new property.

2017-04-11 15:21 UTC, XVincentX requested changes
1. Bump to 0.14
2. Add a test making sure the value is different.

2017-04-11 15:23 UTC, pksunkara commented on package.json
> +  "version": "0.13.8",
From semver

> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

When less than v1, generally, people follow the rule of doing minor changes as patch versions and major changes as minor versions.

2017-04-11 15:23 UTC, XVincentX commented on package.json
> +  "version": "0.13.8",
Ah - ok.

2017-04-11 17:49 UTC, michalholasek commented on test/transformation-test.coffee
> +            assert.equal(setCookieHeaders.length, 3)
Addressed.

2017-04-11 18:44 UTC, XVincentX approved these changes

2017-04-11 18:44 UTC, XVincentX commented
I think we can move ahead!

2017-04-12 08:57 UTC, merged